# Generated by Django 6.0.4 on 2026-05-25 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0003_add_is_public_to_birthreport'),
        ('blog', '0001_initial'),
        ('mirror', '0005_add_engagement_fields'),
        ('psychometrics', '0005_remove_token_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Texto')),
                ('source_type', models.CharField(choices=[('espejo', 'Sesión del Espejo'), ('test', 'Resultado de Test'), ('birth', 'Lectura de Nacimiento'), ('free', 'Texto libre')], default='free', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'En revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='draft', max_length=12)),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='Notas del revisor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_submissions', to='birth.birthreport')),
                ('blog_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='blog.blogpost')),
                ('espejo_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_submissions', to='mirror.conflictsession')),
                ('test_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_submissions', to='psychometrics.testresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postulación al Blog',
                'verbose_name_plural': 'Postulaciones al Blog',
                'ordering': ['-updated_at'],
            },
        ),
    ]
