# Generated by Django 6.0.4 on 2026-05-25 04:11

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Página de Inicio'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_app_text',
            field=models.CharField(default='Comenzar el viaje', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_app_url',
            field=models.URLField(default='https://app.endonautas.cl'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_ebook_text',
            field=models.CharField(default='Descargar Endonautica', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_ebook_url',
            field=models.URLField(default='https://ebook.endonautas.cl'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
