# Generated by Django 6.0.4 on 2026-05-25 05:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_cta_app_text_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Página Simple',
            },
            bases=('wagtailcore.page',),
        ),
    ]
