# Generated by Django 6.0.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#c4813a', help_text='Color HEX para el badge', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='crm.subscriber')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='crm.tag')),
            ],
            options={
                'verbose_name': 'Etiqueta de contacto',
                'verbose_name_plural': 'Etiquetas de contacto',
                'unique_together': {('subscriber', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre interno de la campaña', max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('plain_text_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('target_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='crm.emaillist')),
                ('target_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='crm.segment')),
            ],
            options={
                'verbose_name': 'Campaña manual',
                'verbose_name_plural': 'Campañas manuales',
                'ordering': ['-created_at'],
            },
        ),
    ]
