# Generated by Django 6.0.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_tag_contacttag_broadcast'),
    ]

    operations = [
        # Nuevo campo brevo_message_id en SentEmail
        migrations.AddField(
            model_name='sentemail',
            name='brevo_message_id',
            field=models.CharField(blank=True, help_text='Message-ID de Brevo para tracking de eventos', max_length=255),
        ),
        # Nuevo modelo EmailEvent
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('opened', 'Abierto'), ('clicked', 'Click'), ('bounced', 'Rebotado'), ('unsubscribed', 'Desuscrito'), ('delivered', 'Entregado'), ('spam', 'Spam')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos extra del evento (link clickeado, IP, etc.)')),
                ('occurred_at', models.DateTimeField(help_text='Cuándo ocurrió el evento según Brevo')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se trajo de la API')),
                ('sent_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.sentemail')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='crm.subscriber')),
            ],
            options={
                'verbose_name': 'Evento de email',
                'verbose_name_plural': 'Eventos de email',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['subscriber', 'event_type'], name='crm_emailsg_subscr_5c3f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='crm_emailsg_event_t_8a9f1e_idx'),
        ),
    ]
